def test_import():
    from ..kepclip      import kepclip
    from ..kepoutlier   import kepoutlier
    from ..kepcotrend   import kepcotrendsc
    from ..kepdetrend   import kepdetrend
    from ..kepdiffim    import kepdiffim
    from ..kepextract   import kepextract
    from ..kepft        import kepft
    from ..kepmask      import kepmask
    from ..kepflatten   import kepflatten
    from ..kepfit       import *
    from ..kepfunc      import *
    from ..kepsmooth    import kepsmooth
    from ..kepstddev    import kepstddev
    from ..kepfold      import kepfold
    from ..keptrim      import keptrim
    from ..kepfourier   import ft
    from ..keptrial     import keptrial
    from ..kepdynamic   import kepdynamic
    from ..kepfilter    import kepfilter
    from ..keppixseries import keppixseries
