def test_import():
    from ..lightcurve   import *
    from ..ma02         import *
    from ..orbit        import *
    from ..keparith     import *
    from ..kepmsg       import *
    from ..kepkey       import *
    from ..keparray     import *
    from ..kepfunc      import *
    from ..keplab       import *
    from ..kepfit       import *
    from ..kepio        import *
    from ..kepplot      import *
    from ..kepstat      import *
    from ..kepbls       import *
    from ..kepclip      import *
    from ..kepconvert   import *
    from ..kepcotrend   import *
    from ..kepdetrend   import *
    from ..kepdiffim    import *
    from ..kepdraw      import *
    from ..kepdynamic   import *
    from ..kepextract   import *
    from ..kepffi       import *
    from ..kepfilter    import *
    from ..kepflatten   import *
    from ..kepfold      import *
    from ..kepft        import *
    from ..kephead      import *
    from ..kepimages    import *
    from ..kepmask      import *
    from ..kepoutlier   import *
    from ..keppca       import *
    from ..keppixseries import *
    from ..kepprf       import *
    from ..kepprfphot   import *
    from ..keprange     import *
    from ..kepsmooth    import *
    from ..kepstddev    import *
    from ..kepstitch    import *
    from ..keptimefix   import *
    from ..keptransit   import *
    from ..keptrial     import *
    from ..keptrim      import *
    from ..kepwindow    import *
