def test_import():
    from .. import kepio
    from .. import kepmask
    from .. import kepmsg
    from .. import kepkey
    from .. import kepplot
    from .. import kepstat
    from .. import kepfunc
    from .. import keparray
    from .. import kepprf
    from .. import kepfit
    from .. import kepfold
    from .. import kepclip
    from .. import kepsmooth
    from .. import kepflatten
    from .. import kepdynamic
    from .. import kepstddev
    from .. import kepwindow
    from .. import keptrim
    from .. import keppca
    from .. import kepconvert
    from .. import kepfilter
    from .. import kepextract
    from .. import keptrial
    from .. import kepimages
    from .. import keptimefix
    from .. import kepft
    from .. import kepoutlier
    from .. import kephead
    from .. import keppixseries
